//! Hardcoded, compile-time-checked localization tables.
//!
//! Design (see `doc.md`):
//! - [`Strings`] is the schema: one `SharedString` field per UI string. Built
//!   with the `const fn` `SharedString::new_static`, so every entry is the
//!   zero-allocation `Borrowed(&'static str)` variant and `.clone()` on the
//!   render hot path is free.
//! - Each language is one `pub static <CODE>: Strings = lang!{ ... };` in its
//!   own file. Because `lang!` expands to a full struct literal, the compiler
//!   errors if a language is missing or misspells any key (completeness on the
//!   key axis).
//! - [`Lang`] + its lookup are generated by `languages!`, so the language list
//!   lives in one place and `Lang::strings` is an exhaustive `match`
//!   (completeness on the language axis).
//! - Interpolated strings store a `{}`-placeholder template in a field and are
//!   read through the accessor methods on `impl Strings` (one place, shared
//!   across all languages).

use std::sync::atomic::{AtomicU8, Ordering};

use gpui::SharedString;

mod cs;
mod de;
mod en;
mod es;
mod fr;
mod hi;
mod id;
mod it;
mod ja;
mod ko;
mod nl;
mod pl;
mod pt;
mod ru;
mod sv;
mod th;
mod tr;
mod uk;
mod vi;
mod zh;

/// One immutable string per UI label. See the module docs.
pub struct Strings {
    // --- Transport / footer ---
    pub play: SharedString,
    pub pause: SharedString,
    pub next: SharedString,
    pub previous: SharedString,
    pub shuffle: SharedString,
    pub repeat_mode: SharedString,
    pub volume: SharedString,
    pub mute: SharedString,
    pub unmute: SharedString,
    pub queue: SharedString,
    pub remove_from_queue: SharedString,
    pub queue_is_empty: SharedString,

    // --- Track-row actions ---
    pub add_to_playlist: SharedString,
    pub remove_from_playlist: SharedString,
    pub add_to_queue: SharedString,
    pub add_album_to_queue: SharedString,

    // --- Header / navigation ---
    pub settings: SharedString,
    pub search_placeholder: SharedString,
    pub tab_albums: SharedString,
    pub tab_artists: SharedString,
    pub tab_liked: SharedString,
    pub tab_playlists: SharedString,

    // --- Library empty / loading states ---
    pub scanning: SharedString,
    pub no_music_folders_configured: SharedString,
    pub add_music_folder: SharedString,
    pub no_albums_found: SharedString,
    pub no_albums_match: SharedString,
    pub no_artists_found: SharedString,
    pub no_artists_match: SharedString,
    pub no_tracks_for_album: SharedString,
    pub no_tracks_match: SharedString,
    pub no_tracks_for_artist: SharedString,
    pub no_liked_tracks: SharedString,
    pub no_liked_match: SharedString,
    pub playlist_is_empty: SharedString,
    pub unknown: SharedString,

    // --- Playlists ---
    pub filter_playlists: SharedString,
    pub playlist_name: SharedString,
    pub name_new_playlist: SharedString,
    pub create: SharedString,
    pub cancel: SharedString,
    pub no_playlists_yet: SharedString,
    pub no_playlists_match: SharedString,
    pub create_new_playlist: SharedString,
    pub new_playlist_name: SharedString,
    pub new_playlist: SharedString,
    pub delete: SharedString,

    // --- Settings page ---
    pub settings_interface: SharedString,
    pub settings_library: SharedString,
    pub theme: SharedString,
    pub theme_desc: SharedString,
    pub system: SharedString,
    pub language: SharedString,
    pub language_desc: SharedString,
    pub exclusive_mode_button: SharedString,
    pub exclusive_mode_button_desc: SharedString,
    pub repeat_shuffle: SharedString,
    pub repeat_shuffle_desc: SharedString,
    pub time_labels: SharedString,
    pub time_labels_desc: SharedString,
    pub liked_tracks: SharedString,
    pub liked_tracks_desc: SharedString,
    pub playlists_desc: SharedString,
    pub track_duration: SharedString,
    pub track_duration_desc: SharedString,
    pub action_buttons: SharedString,
    pub action_buttons_desc: SharedString,
    pub artist_name: SharedString,
    pub artist_name_desc: SharedString,
    pub music_folders: SharedString,
    pub music_folders_desc: SharedString,
    pub no_folders_added: SharedString,
    pub show_in_finder: SharedString,
    pub remove: SharedString,
    pub add_folder: SharedString,

    // --- Audio settings ---
    pub audio_device: SharedString,
    pub exclusive_mode_title: SharedString,
    pub bit_perfect_playback: SharedString,
    pub not_bit_perfect: SharedString,
    pub bp_not_exclusive: SharedString,
    pub bp_system_muted: SharedString,
    pub bp_no_source: SharedString,
    pub fix_volume: SharedString,
    pub fix_volume_tooltip: SharedString,
    pub select_audio_device: SharedString,
    pub exclusive_click_disable: SharedString,
    pub shared_click_enable: SharedString,
    pub default_suffix: SharedString,

    // --- App menu ---
    pub quit_pawse: SharedString,
    pub rescan_library: SharedString,
    pub menu_file: SharedString,

    // --- Templated (read via the accessor methods below) ---
    pub disc_t: SharedString,
    pub audio_spec_t: SharedString,
    pub bitrate_t: SharedString,
    pub n_tracks_one: SharedString,
    pub n_tracks_other: SharedString,
    pub bp_system_volume_t: SharedString,
    pub bp_app_volume_t: SharedString,
    pub bp_sample_rate_t: SharedString,
    pub bp_bit_depth_t: SharedString,
    pub failed_exclusive_t: SharedString,
    pub failed_switch_device_t: SharedString,
    pub failed_save_settings_t: SharedString,
}

/// Replace each `{}` marker in `template` with the next arg, in order.
fn fill(template: &str, args: &[&str]) -> String {
    let mut out = String::with_capacity(template.len());
    let mut parts = template.split("{}");
    if let Some(first) = parts.next() {
        out.push_str(first);
    }
    for (arg, part) in args.iter().zip(parts) {
        out.push_str(arg);
        out.push_str(part);
    }
    out
}

impl Strings {
    /// Section header for a multi-disc album, e.g. "Disc 2".
    pub fn disc(&self, disc: u32) -> String {
        fill(&self.disc_t, &[&disc.to_string()])
    }

    /// Sample-rate / bit-depth line, e.g. "44.1 kHz · 24-bit". `khz` is already
    /// formatted by the caller (integer vs one-decimal).
    pub fn audio_spec(&self, khz: &str, bit_depth: u32) -> String {
        fill(&self.audio_spec_t, &[khz, &bit_depth.to_string()])
    }

    /// Bitrate line, e.g. "320 kbps".
    pub fn bitrate(&self, kbps: u32) -> String {
        fill(&self.bitrate_t, &[&kbps.to_string()])
    }

    /// Track-count label, e.g. "1 track" / "12 tracks". Two-form plural
    /// (singular when `n == 1`); languages with richer plural rules fall back
    /// to the general form.
    pub fn n_tracks(&self, n: i64) -> String {
        let template = if n == 1 {
            &self.n_tracks_one
        } else {
            &self.n_tracks_other
        };
        fill(template, &[&n.to_string()])
    }

    pub fn bp_system_volume(&self, value: &str) -> String {
        fill(&self.bp_system_volume_t, &[value])
    }

    pub fn bp_app_volume(&self, value: &str) -> String {
        fill(&self.bp_app_volume_t, &[value])
    }

    pub fn bp_sample_rate(&self, source_hz: u32, device_hz: u32) -> String {
        fill(
            &self.bp_sample_rate_t,
            &[&source_hz.to_string(), &device_hz.to_string()],
        )
    }

    pub fn bp_bit_depth(&self, source: u32) -> String {
        fill(&self.bp_bit_depth_t, &[&source.to_string()])
    }

    pub fn failed_exclusive(&self, err: &str) -> String {
        fill(&self.failed_exclusive_t, &[err])
    }

    pub fn failed_switch_device(&self, err: &str) -> String {
        fill(&self.failed_switch_device_t, &[err])
    }

    pub fn failed_save_settings(&self, err: &str) -> String {
        fill(&self.failed_save_settings_t, &[err])
    }
}

/// Build a `Strings` literal from `key: "value"` pairs. Expands to a full struct
/// literal, so a missing or misspelled key is a compile error.
#[macro_export]
macro_rules! lang {
    ($($key:ident : $val:literal),* $(,)?) => {
        $crate::i18n::Strings {
            $( $key: ::gpui::SharedString::new_static($val) ),*
        }
    };
}

macro_rules! languages {
    ($($variant:ident => ($code:literal, $name:literal, $table:path)),* $(,)?) => {
        /// A supported UI language.
        #[derive(Copy, Clone, PartialEq, Eq, Debug)]
        pub enum Lang {
            $($variant),*
        }

        impl Lang {
            /// All languages, in menu order.
            pub fn all() -> &'static [Lang] {
                &[$(Lang::$variant),*]
            }

            /// BCP-47-ish short code persisted in settings (e.g. "en", "zh").
            pub fn code(self) -> &'static str {
                match self { $(Lang::$variant => $code),* }
            }

            /// Endonym shown in the language picker (not itself localized).
            pub fn display_name(self) -> &'static str {
                match self { $(Lang::$variant => $name),* }
            }

            /// The string table for this language.
            pub fn strings(self) -> &'static Strings {
                match self { $(Lang::$variant => &$table),* }
            }

            /// Exact match on a stored code.
            pub fn from_code(code: &str) -> Option<Lang> {
                match code {
                    $($code => Some(Lang::$variant),)*
                    _ => None,
                }
            }
        }
    };
}

languages! {
    En => ("en", "English", en::EN),
    Es => ("es", "Español", es::ES),
    Zh => ("zh", "简体中文", zh::ZH),
    Pt => ("pt", "Português (Brasil)", pt::PT),
    Ru => ("ru", "Русский", ru::RU),
    Ja => ("ja", "日本語", ja::JA),
    De => ("de", "Deutsch", de::DE),
    Fr => ("fr", "Français", fr::FR),
    Ko => ("ko", "한국어", ko::KO),
    It => ("it", "Italiano", it::IT),
    Tr => ("tr", "Türkçe", tr::TR),
    Pl => ("pl", "Polski", pl::PL),
    Nl => ("nl", "Nederlands", nl::NL),
    Uk => ("uk", "Українська", uk::UK),
    Vi => ("vi", "Tiếng Việt", vi::VI),
    Id => ("id", "Bahasa Indonesia", id::ID),
    Th => ("th", "ไทย", th::TH),
    Cs => ("cs", "Čeština", cs::CS),
    Sv => ("sv", "Svenska", sv::SV),
    Hi => ("hi", "हिन्दी", hi::HI),
}

impl Lang {
    /// Best-effort mapping from an OS locale string (e.g. "ru-RU", "zh_Hans_CN")
    /// to a supported language, falling back to English.
    pub fn from_locale(locale: &str) -> Lang {
        let prefix = locale
            .split(['-', '_'])
            .next()
            .unwrap_or("")
            .to_ascii_lowercase();
        Self::from_code(&prefix).unwrap_or(Lang::En)
    }

    /// Position in `all()` — stable as long as the `languages!` order is stable.
    pub fn index(self) -> usize {
        Self::all().iter().position(|&l| l == self).unwrap_or(0)
    }

    /// Inverse of `index`; out-of-range falls back to English.
    pub fn from_index(i: usize) -> Lang {
        Self::all().get(i).copied().unwrap_or(Lang::En)
    }
}

/// Active UI language, as a `Lang` index. Derived cache of the persisted
/// `LangChoice` in `pawse`; updated only at sync points. Defaults to index 0
/// (English) until the app sets it at startup.
static ACTIVE_LANG: AtomicU8 = AtomicU8::new(0);

/// Set the active language (call on startup and on every language change).
pub fn set_active(lang: Lang) {
    ACTIVE_LANG.store(lang.index() as u8, Ordering::Relaxed);
}

/// The active language.
pub fn active() -> Lang {
    Lang::from_index(ACTIVE_LANG.load(Ordering::Relaxed) as usize)
}

/// The active language's string table. Allocation-free, no syscall, no hashmap.
pub fn strings() -> &'static Strings {
    active().strings()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn twenty_languages() {
        assert_eq!(Lang::all().len(), 20);
    }

    #[test]
    fn every_language_resolves_and_round_trips() {
        for &lang in Lang::all() {
            // Table is reachable and a representative key is populated.
            assert!(!lang.strings().play.is_empty());
            assert_eq!(Lang::from_code(lang.code()), Some(lang));
        }
    }

    #[test]
    fn locale_detection() {
        assert_eq!(Lang::from_locale("ru-RU"), Lang::Ru);
        assert_eq!(Lang::from_locale("zh_Hans_CN"), Lang::Zh);
        assert_eq!(Lang::from_locale("xx-YY"), Lang::En);
    }

    #[test]
    fn active_lang_round_trips() {
        for &lang in Lang::all() {
            assert_eq!(Lang::from_index(lang.index()), lang);
            set_active(lang);
            assert_eq!(active(), lang);
            assert_eq!(strings().play, lang.strings().play);
        }
        set_active(Lang::En);
    }

    #[test]
    fn fill_handles_placeholders() {
        assert_eq!(fill("Disc {}", &["2"]), "Disc 2");
        assert_eq!(
            fill("{} kHz · {}-bit", &["44.1", "24"]),
            "44.1 kHz · 24-bit"
        );
        assert_eq!(fill("no placeholders", &[]), "no placeholders");
    }
}
