[package]
name = "subsonic"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
log = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = "3"
md-5 = "0.10"
thiserror = "2.0"
server_http = { path = "../server_http" }

[lib]
path = "src/lib.rs"

[lints]
workspace = true
