[package]
name = "artist_info"
version.workspace = true
edition.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
cover_search = { path = "../cover_search" }
log = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = "3"

[dev-dependencies]
rstest = "0.26"

[lints]
workspace = true
