name: Audit

on:
  schedule:
    - cron: "37 14 * * 3"
  push:
    paths:
      - "**/Cargo.lock"
      - "**/Cargo.toml"
      - ".github/workflows/audit.yml"
  workflow_dispatch:

jobs:
  audit:
    name: cargo audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit

      - run: cargo audit
